Repository SE-TINF22B2/G5-DuoGradus, pull requests merged in 2024-06, with the labels that each got.

#212 Added pull request template
  .github/pull_request_template.md
Labels: enhancement

#211 Translated GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
Labels: bug, enhancement

#213 Updated project guideline
  docs/development/project-guideline.md
Labels: documentation, enhancement

#216 Volume for DB Persistence
  .gitignore
  backend/package.json
  docker-compose.yml
Labels: enhancement, backend

#219 Translated pull request template
  .github/pull_request_template.md
Labels: bug

#218 Status Report KW22
  docs/.vitepress/config.mts
  docs/reports/2024-kw21.md
  docs/reports/2024-kw22.md
Labels: documentation

#223 add technical documentation for the frontend
  docs/development/frontend/technical documentation.md
Labels: frontend

#229 Status Report KW23
  docs/.vitepress/config.mts
  docs/reports/2024-kw23.md
Labels: documentation, enhancement

#230 Missing translation in backend documentation
  docs/.vitepress/config.mts
  docs/development/backend/authentication.md
Labels: documentation

#231 Endpoint for registering new users
  backend/package-lock.json
  backend/package.json
  backend/src/api/user/patch.user.dto.ts
  backend/src/api/user/register.user.dto.ts
  backend/src/api/user/user.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/db/repositories/user.repository.ts
  docs/public/api/schema.yaml
Labels: backend

#239 Enable Password Hashing in Registration
  backend/src/api/user/user.controller.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
Labels: bug, backend

#237 Add Points for Tasks
  backend/src/app/streaks/streak.module.ts
  backend/src/app/streaks/streak.service.ts
  backend/src/app/tasks/dto/TaskStartStopDTO.ts
  backend/src/app/tasks/task.controller.ts
  backend/src/app/tasks/task.module.ts
  backend/src/app/tasks/task.service.spec.ts
  backend/src/app/tasks/task.service.ts
  backend/src/app/tasks/tasks/static/task.1.ts
  backend/src/app/tasks/tasks/static/task2.ts
  backend/src/app/tasks/tasks/static/task3.ts
  backend/src/app/tasks/tasks/task.types.ts
Labels: enhancement, backend

#234 Provide Goals
  backend/prisma/migrations/20240614204325_/migration.sql
  backend/prisma/schema.prisma
  backend/src/app.module.ts
  backend/src/app/goals/goal.controller.ts
  backend/src/app/goals/goal.module.ts
  backend/src/app/goals/goal.service.spec.ts
  backend/src/app/goals/goal.service.ts
  backend/src/db/prisma.module.ts
  backend/src/db/repositories/goal.repository.ts
Labels: enhancement, backend

#247 add missing comments
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/components/atoms/challenge-button/challenge-button.component.scss
  frontend/src/app/components/atoms/challenge-button/challenge-button.component.ts
  frontend/src/app/components/atoms/friend-card/friend-card.component.scss
  frontend/src/app/components/atoms/friend-card/friend-card.component.ts
  frontend/src/app/components/atoms/header/header.component.scss
  frontend/src/app/components/atoms/header/header.component.ts
  frontend/src/app/components/atoms/inputfield/inputfield.component.scss
  frontend/src/app/components/atoms/loader/loader.component.scss
  frontend/src/app/components/atoms/searchbar/searchbar.component.scss
  frontend/src/app/components/atoms/searchbar/searchbar.component.ts
  frontend/src/app/components/atoms/settingsentry/settingsentry.component.scss
  frontend/src/app/components/atoms/statistic-entry/statistic-entry.component.scss
  frontend/src/app/components/atoms/stopbutton/stopbutton.component.scss
  frontend/src/app/components/atoms/stopbutton/stopbutton.component.ts
  frontend/src/app/components/atoms/toast/toast.component.scss
  frontend/src/app/components/atoms/user-card/user-card.component.scss
  frontend/src/app/components/organisms/challenge-dialog/challenge-dialog.component.scss
  frontend/src/app/components/organisms/challenge-dialog/challenge-dialog.component.ts
  frontend/src/app/components/organisms/delete-dialog/delete-dialog.component.scss
  frontend/src/app/components/organisms/delete-dialog/delete-dialog.component.ts
  frontend/src/app/components/organisms/footer/footer.component.scss
  frontend/src/app/components/organisms/footer/footer.component.ts
  frontend/src/app/components/organisms/loginform/loginform.component.scss
  frontend/src/app/components/organisms/loginform/loginform.component.ts
  frontend/src/app/components/organisms/ranking-table/ranking-table.component.scss
  frontend/src/app/components/organisms/roadmap/roadmap.component.scss
  frontend/src/app/components/organisms/roadmap/roadmap.component.ts
  frontend/src/app/components/organisms/signupform/signupform.component.scss
  frontend/src/app/components/organisms/signupform/signupform.component.ts
  frontend/src/app/components/organisms/statistic-header/statistic-header.component.scss
  frontend/src/app/components/organisms/statistic-header/statistic-header.component.ts
  frontend/src/app/components/pages/addfriendpage/addfriendpage.component.scss
  frontend/src/app/components/pages/addfriendpage/addfriendpage.component.ts
  frontend/src/app/components/pages/authenticationpage/authenticationpage.component.scss
  frontend/src/app/components/pages/friendpage/friendpage.component.scss
  frontend/src/app/components/pages/friendpage/friendpage.component.ts
  frontend/src/app/components/pages/landingpage/landingpage.component.scss
  frontend/src/app/components/pages/landingpage/landingpage.component.ts
  frontend/src/app/components/pages/mainpage/mainpage.component.scss
  frontend/src/app/components/pages/mainpage/mainpage.component.ts
  frontend/src/app/components/pages/profilepage/profilepage.component.scss
  frontend/src/app/components/pages/profilepage/profilepage.component.ts
  frontend/src/app/components/pages/ranking-page/ranking-page.component.scss
  frontend/src/app/components/pages/ranking-page/ranking-page.component.ts
  frontend/src/app/components/pages/settingspage/settingspage.component.scss
  frontend/src/app/components/pages/settingspage/settingspage.component.ts
  frontend/src/app/pipes/timer.pipe.ts
  frontend/src/app/pipes/userfilter.pipe.ts
  frontend/src/styles.scss
Labels: frontend

#249 Add architecture to docs
  docs/development/backend/overview.md
  docs/public/concept/architecture.jpg
  docs/public/concept/backend_er-diagram.jpg
Labels: documentation, enhancement

#250 Improve Backend README
  backend/README.md
Labels: documentation, enhancement

#252 Added project takeover to docs
  docs/.vitepress/config.mts
  docs/project/project-takeover.md
Labels: documentation, enhancement
