Repository SE-TINF22B2/G5-DuoGradus, pull requests merged in 2024-05, with the labels that each got.

#153 Add Docker image for backend
  backend/.dockerignore
  backend/Dockerfile
  backend/package.json
  docker-compose.yml
  docs/.vitepress/config.mts
  docs/development/deployment.md
  frontend/.dockerignore
  frontend/Caddyfile
  frontend/Dockerfile
  frontend/angular.json
Labels: documentation, frontend, backend

#164 Changes to the API schema
  docs/public/api/schema.yaml
Labels: documentation, required

#181 Fix Frontend Action
  .github/workflows/frontend.yml
  frontend/angular.json
  frontend/package.json
  frontend/src/app/components/pages/profilepage/profilepage.component.html
  frontend/src/app/components/pages/profilepage/profilepage.component.spec.ts
Labels: bug, frontend

#182 Unified GitHub Actions
  .github/workflows/docs.yml
  docs/package.json
Labels: documentation, enhancement

#184 Status Report KW19
  docs/.vitepress/config.mts
  docs/reports/2024-kw19.md
Labels: documentation, 🚨🚨 URGENT 🚨🚨

#179 Feature/settings
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/atoms/settingsentry/settingsentry.component.html
  frontend/src/app/components/atoms/settingsentry/settingsentry.component.scss
  frontend/src/app/components/atoms/settingsentry/settingsentry.component.spec.ts
  frontend/src/app/components/atoms/settingsentry/settingsentry.component.ts
  frontend/src/app/components/pages/profilepage/profilepage.component.spec.ts
  frontend/src/app/components/pages/settingspage/settingspage.component.html
  frontend/src/app/components/pages/settingspage/settingspage.component.scss
  frontend/src/app/components/pages/settingspage/settingspage.component.spec.ts
  frontend/src/app/components/pages/settingspage/settingspage.component.ts
  frontend/src/assets/icons/close-settings.svg
Labels: frontend

#189 Fixed `docs` mockup links
  docs/project/user-interface.md
Labels: bug, documentation

#195 Code documentation guideline
  docs/.vitepress/config.mts
  docs/development/code-documentation.md
Labels: documentation, enhancement

#198 Added User Interface to used spoken languages
  docs/development/project-guideline.md
Labels: documentation, enhancement

#200 Status Report KW21
  docs/.vitepress/config.mts
  docs/reports/2024-kw20.md
  docs/reports/2024-kw21.md
Labels: documentation

#204 Disable coverage on verify
  backend/package.json
Labels: 🚨🚨 URGENT 🚨🚨
